# Базовая конфигурация Sigma

# Настройки полей
title: Windows Field Mappings
order: 10
backends:
  - splunk
  - elasticsearch

# Сопоставление полей для Windows Event Log
fieldmappings:
  EventID: event_id
  CommandLine: command_line
  Image: process_path
  ParentImage: parent_process_path
  User: user_name
  TargetObject: target_object
  TargetFilename: target_file
  SourceImage: source_process_path
  DestinationIp: dest_ip
  DestinationHostname: dest_host
  DestinationPort: dest_port
  SourcePort: src_port
  SourceIp: src_ip
  SourceHostname: src_host
  SubjectUserName: subject_user_name
  ObjectName: object_name
  ShareName: share_name
  ServiceName: service_name
  TaskName: task_name
  ProcessId: process_id
  ParentProcessId: parent_process_id

# Преобразования значений
valuemappings:
  EventID:
    - source: Security
      target: Security
    - source: System
      target: System
    - source: Application
      target: Application
    - source: "Microsoft-Windows-Sysmon/Operational"
      target: Sysmon

# Обработка логов
logsources:
  windows-security:
    product: windows
    service: security
    conditions:
      EventLog: Security
  
  windows-system:
    product: windows
    service: system
    conditions:
      EventLog: System
      
  windows-application:
    product: windows
    service: application
    conditions:
      EventLog: Application
      
  windows-sysmon:
    product: windows
    service: sysmon
    conditions:
      EventLog: Microsoft-Windows-Sysmon/Operational

# Настройки обработки
processing:
  # Преобразование временных меток
  timestamps:
    format: ISO8601
    timezone: UTC
    
  # Обработка полей
  fields:
    # Приведение к нижнему регистру
    lowercase:
      - command_line
      - process_path
      - user_name
      - target_file
      
    # Нормализация путей
    normalize_paths:
      - process_path
      - parent_process_path
      - target_file
      - source_process_path
      
    # Нормализация пользователей
    normalize_users:
      - user_name
      - subject_user_name

# Настройки правил
rules:
  # Минимальный уровень важности
  min_level: medium
  
  # Категории правил
  categories:
    - attack.execution
    - attack.persistence
    - attack.privilege_escalation
    - attack.defense_evasion
    - attack.credential_access
    - attack.discovery
    - attack.lateral_movement
    - attack.collection
    - attack.command_and_control
    - attack.exfiltration
    - attack.impact 