# Правила для обнаружения изменений в переменных окружения

rules:
  # Модификация системных переменных
  system_variables:
    paths:
      - "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment"
    indicators:
      - "Path=.*\\Windows\\Temp\\.*"
      - "Path=.*\\AppData\\Local\\Temp\\.*"
      - "Path=.*\\Users\\Public\\.*"
      - "Path=.*\\ProgramData\\.*"
      - "PATHEXT=.*\\.COM;.*"  # Добавление нестандартных расширений
      - "PATHEXT=.*\\.EXE;.*"
      - "PATHEXT=.*\\.BAT;.*"
      - "PATHEXT=.*\\.CMD;.*"
      - "PATHEXT=.*\\.VBS;.*"
      - "PATHEXT=.*\\.JS;.*"
      
  # Модификация пользовательских переменных
  user_variables:
    paths:
      - "HKCU\\Environment"
    indicators:
      - "Path=.*\\Windows\\Temp\\.*"
      - "Path=.*\\AppData\\Local\\Temp\\.*"
      - "Path=.*\\Users\\Public\\.*"
      - "Path=.*\\ProgramData\\.*"
      
  # Модификация переменных для служб
  service_variables:
    paths:
      - "HKLM\\SYSTEM\\CurrentControlSet\\Services\\.*\\Environment"
    indicators:
      - ".*\\Windows\\Temp\\.*"
      - ".*\\AppData\\Local\\Temp\\.*"
      - ".*\\Users\\Public\\.*"
      - ".*\\ProgramData\\.*"
      
  # Модификация путей поиска DLL
  dll_search_paths:
    paths:
      - "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\KnownDLLs"
    indicators:
      - ".*\\.dll=.*\\Windows\\Temp\\.*"
      - ".*\\.dll=.*\\AppData\\Local\\Temp\\.*"
      - ".*\\.dll=.*\\Users\\Public\\.*"
      
  # Модификация путей для .NET
  dotnet_paths:
    paths:
      - "HKLM\\SOFTWARE\\Microsoft\\.NETFramework"
    indicators:
      - "DeveloperPath=.*\\Windows\\Temp\\.*"
      - "DeveloperPath=.*\\AppData\\Local\\Temp\\.*"
      - "DeveloperPath=.*\\Users\\Public\\.*"

  environment_changes:
    description: "Подозрительные изменения переменных окружения"
    paths:
      - "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment"
      - "HKCU\\Environment"
      - "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\User Shell Folders"
    indicators:
      - "Path=.*\\AppData\\Local\\Temp\\.*"
      - "Path=.*\\Users\\Public\\.*"
      - "PATHEXT=.*\\.COM;.*"
      - "PATHEXT=.*\\.EXE;.*"
      - "PATHEXT=.*\\.BAT;.*"
      - "PATHEXT=.*\\.CMD;.*"
    severity: medium
    tags:
      - environment
      - configuration 