# Правила для обнаружения изменений в настройках безопасности

rules:
  # Отключение защитных механизмов
  security_features:
    paths:
      - "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System"
      - "HKLM\\SOFTWARE\\Microsoft\\Windows Defender"
      - "HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows Defender"
    indicators:
      - "EnableLUA=0"                # Отключение UAC
      - "DisableAntiSpyware=1"       # Отключение антишпионского ПО
      - "DisableAntiVirus=1"         # Отключение антивируса
      - "DisableRealtimeMonitoring=1" # Отключение мониторинга в реальном времени
      - "DisableBehaviorMonitoring=1" # Отключение поведенческого анализа
      - "DisableIOAVProtection=1"     # Отключение сканирования загрузок
      
  # Изменения в политиках аудита
  audit_policy:
    paths:
      - "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa"
      - "HKLM\\SYSTEM\\CurrentControlSet\\Services\\EventLog"
    indicators:
      - "AuditLevel=0"              # Отключение аудита
      - "CrashOnAuditFail=0"        # Отключение остановки при сбое аудита
      - "FullPrivilegeAuditing=0"   # Отключение полного аудита привилегий
      
  # Изменения в настройках LSA
  lsa_settings:
    paths:
      - "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa"
    indicators:
      - "RestrictAnonymous=0"       # Разрешение анонимного доступа
      - "everyoneincludesanonymous=1" # Включение анонимного доступа
      - "NoLMHash=0"                # Разрешение слабого хеширования
      - "LMCompatibilityLevel=[01]" # Слабый уровень совместимости
      
  # Изменения в настройках WDigest
  wdigest_settings:
    paths:
      - "HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\WDigest"
    indicators:
      - "UseLogonCredential=1"      # Хранение паролей в памяти
      
  # Изменения в настройках удаленного доступа
  remote_access:
    paths:
      - "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server"
      - "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Remote Assistance"
    indicators:
      - "fDenyTSConnections=0"      # Разрешение RDP
      - "fAllowToGetHelp=1"         # Разрешение удаленной помощи
      
  # Изменения в настройках брандмауэра
  firewall_settings:
    paths:
      - "HKLM\\SYSTEM\\CurrentControlSet\\Services\\SharedAccess\\Parameters\\FirewallPolicy"
    indicators:
      - "EnableFirewall=0"          # Отключение брандмауэра
      - "DoNotAllowExceptions=0"    # Разрешение исключений
      
  # Изменения в настройках DEP/ASLR
  exploit_protection:
    paths:
      - "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management"
    indicators:
      - "MoveImages=0"              # Отключение ASLR
      - "DisableExceptionChainValidation=1" # Отключение валидации SEH 

  security_settings:
    description: "Подозрительные изменения настроек безопасности"
    paths:
      - "HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders"
      - "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa"
      - "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System"
      - "HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\System"
    indicators:
      - "DisableAntiSpyware=1"
      - "DisableAntiVirus=1"
      - "EnableLUA=0"
      - "ConsentPromptBehaviorAdmin=0"
      - "FilterAdministratorToken=0"
      - "EnableUIADesktopToggle=1"
    severity: high
    tags:
      - security
      - configuration 